services:
  # minio:
  #   image: bitnami/minio:latest
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     - MINIO_ROOT_USER=jumpstart
  #     - MINIO_ROOT_PASSWORD=jumpstart
  #     - MINIO_DEFAULT_BUCKETS=jumpstart
  #   volumes:
  #     - jumpstart-store:/bitnami/minio/data

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - jumpstart-pg:/var/lib/postgresql/data

volumes:
  # jumpstart-store:
  jumpstart-pg:
